const images = {
  global: {
    delete: require('../assets/images/global/delete.png'),
    arrow_down: require('../assets/images/global/arrow_down.png'),
    calender: require('../assets/images/global/calendar.png'),
    search: require('../assets/images/global/search.png'),
    phone: require('../assets/images/global/phone.png'),
    key: require('../assets/images/global/key.png'),
    arrow_back: require('../assets/images/global/arrow_back.png'),
    arrow_right: require('../assets/images/global/arrow_right.png'),
  },
  tab: {
    bars: require('../assets/images/tab/bars_chart.png'),
    profile: require('../assets/images/tab/profile.png'),
    transfer: require('../assets/images/tab/transfer.png'),
    weblog: require('../assets/images/tab/weblog.png'),
  },
  button: {
    GreenBtn: require('../assets/images/Button/button.png'),
    GreenBtn2: require('../assets/images/Button/largeButton.png'),
    redBtn: require('../assets/images/Button/redBtn.png'),
  },
  example: {
    bit: require('../assets/images/example/bit.png'),
    pm: require('../assets/images/example/pm.png'),
    web2: require('../assets/images/example/web2.png'),
    bitcoinC: require('../assets/images/example/bitcoinC.webp'),
    dash: require('../assets/images/example/dash.webp'),
    ethereum: require('../assets/images/example/ethereum.webp'),
    litecoin: require('../assets/images/example/litecoin.webp'),
    tether: require('../assets/images/example/tether.webp'),
    tron: require('../assets/images/example/tron.webp'),
    xrp: require('../assets/images/example/xrp.webp'),
    Rial: require('../assets/images/example/Rial.png'),
  },
  login: {
    dates: require('../assets/images/login/dates.png'),
    eye: require('../assets/images/login/eye.png'),
    mail: require('../assets/images/login/mail.png'),
    males: require('../assets/images/login/males.png'),
    phone: require('../assets/images/login/phone.png'),
    lock: require('../assets/images/login/lock.png'),
  },
};
export default images;
