import ProfileScreen from './ProfileScreen';
import BuyingScreen from './BuyingScreen';
import WeblogScreen from './WeblogScreen';
import PricesScreen from './PricesScreen';
import LoginScreen from './PricesScreen';
import SplashScreen from './SplashScreen';
export const Prices = PricesScreen;
export const Profile = ProfileScreen;
export const Buying = BuyingScreen;
export const Weblog = WeblogScreen;
export const Login = LoginScreen;
export const Splash = SplashScreen;
